debug: false
server:
  address: 127.0.0.1
  port: 8771
management:
  server:
    port: 8770
# ===============================
# = Log To File Config
# ===============================
logging:
  path: logs/gateway-server
  pattern:
    file: '[%date{yyyy-MM-dd HH:mm:ss.SSS}] [ %-5level] [%thread] %logger{96} [%X{lineno}] - %msg%n'
  file: ${logging.path}/${spring.application.name}.log
logging.file.max-size: 5MB
logging.file.max-history: 30
# ===============================
# = Eureka Config
# ===============================
eureka:
  instance:
    ip-address: ${server.address}
    instance-id: ${spring.application.name}:${server.address}:${server.port}:v${info.version}:${spring.profiles.active}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
# ===============================
# = Spring Config
# ===============================
spring:
  redis:
    url: redis://127.0.0.1:6379
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: 127.0.0.1:9092