# ===============================
# = Log To File Config
# ===============================
logging:
  file:
    max-size: 5MB
    max-history: 30
  level:
    com.alibaba.nacos.client.naming: warn
# ===============================
# = Spring Config
# ===============================
spring:
  redis:
    url: redis://127.0.0.1:6379
  kafka:
    bootstrap-servers: ${spring.cloud.stream.kafka.binder.brokers}
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: 127.0.0.1:9092
          # 0代表：不进行消息接收是否成功的确认(默认值)；
          # 1代表：当Leader副本接收成功后，返回接收成功确认信息；
          # -1代表：当Leader和Follower副本都接收成功后，返回接收成功确认信息；
          required-acks: -1
  # ===============================
  # = JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  # ===============================
  # = DATA SOURCE
  # ===============================
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      pool-name: plm
      max-lifetime: 480000
      idle-timeout: 300000
      read-only: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
# ===============================
# = Feign Config
# ===============================
feign:
  httpclient:
    enabled: false
    max-connections: 1000
    time-to-live: 900
    time-to-live-unit: seconds
    follow-redirects: true
  okhttp:
    enabled: true
  sentinel:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 30000
        loggerLevel: full
# ===============================
# = Security Config
# ===============================
security:
  oauth2:
    resource:
      token-info-uri: http://oauth2-server/oauth/check_token
    client:
      client-id: 8a80cb816d2eb97f016d2eba04710000
      client-secret: 2523342F2BD345EA9658452A289364AA
acp:
  swagger:
    enabled: true
  cloud:
    zookeeper:
      connect: 127.0.0.1:21810