debug: false
server:
  address: 127.0.0.1
  port: 8875
management:
  server:
    port: 8874
# ===============================
# = Log To File Config
# ===============================
logging:
  path: logs/workflow-server
  pattern:
    file: '[%date{yyyy-MM-dd HH:mm:ss.SSS}] [ %-5level] [%thread] %logger{96} [%X{lineno}] - %msg%n'
  file: ${logging.path}/${spring.application.name}.log
logging.file.max-size: 5MB
logging.file.max-history: 30
# ===============================
# = Eureka Config
# ===============================
eureka:
  instance:
    ip-address: ${server.address}
    instance-id: ${spring.application.name}:${server.address}:${server.port}:v${info.version}:${spring.profiles.active}
info:
  instance-id: ${eureka.instance.instance-id}
# ===============================
# = Spring Config
# ===============================
spring:
  devtools:
    restart:
      enabled: true
  redis:
    url: redis://127.0.0.1:6379
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  cloud:
    bus:
      id: ${eureka.instance.instance-id}
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: 127.0.0.1:9092
  # ===============================
  # = JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  # ===============================
  # = DATA SOURCE
  # ===============================
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/acp-admin-flowable?autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC&useSSL=false
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
# ===============================
# = Security Config
# ===============================
security:
  oauth2:
    client:
      client-id: 8a80cb816c0a5d4f016c0a5e0c020000
      client-secret: 2523342F2BD345EA9658452A289364AA
acp:
  swagger:
    enabled: true