server:
  port: ${acp_server_port:9099}
# ===============================
# = Log To File Config
# ===============================
logging:
  file:
    path: ${acp_log_path:logs/${spring.application.name}}
    name: ${logging.file.path}/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
  level:
    com.alibaba.nacos.client: warn
# ===============================
# = Spring Config
# ===============================
spring:
  security:
    user:
      name: ${acp_admin_username:admin}
      password: ${acp_admin_password:888888}
  cloud:
    nacos:
      discovery:
        metadata:
          user.name: ${spring.security.user.name}
          user.password: ${spring.security.user.password}