server:
  address: 127.0.0.1
  port: 9099
management:
  server:
    port: 9098
# ===============================
# = Log To File Config
# ===============================
logging:
  path: logs/admin-server
  pattern:
    file: '[%date{yyyy-MM-dd HH:mm:ss.SSS}] [ %-5level] [%thread] %logger{96} [%X{lineno}] - %msg%n'
  file: ${logging.path}/${spring.application.name}.log
logging.file.max-size: 5MB
logging.file.max-history: 30
logging.level.com.alibaba.nacos.client.naming: warn
# ===============================
# = Spring Config
# ===============================
spring:
  security:
    user:
      name: admin
      password: 888888
  cloud:
    nacos:
      discovery:
        ip: ${server.address}
        metadata:
          user.name: ${spring.security.user.name}
          user.password: ${spring.security.user.password}