server:
  address: 127.0.0.1
  port: 8871
management:
  server:
    port: 8870
# ===============================
# = Log To File Config
# ===============================
logging:
  path: logs/route-server
  pattern:
    file: '[%date{yyyy-MM-dd HH:mm:ss.SSS}] [ %-5level] [%thread] %logger{96} [%X{lineno}] - %msg%n'
  file: ${logging.path}/${spring.application.name}.log
logging.file.max-size: 5MB
logging.file.max-history: 30
logging.level.com.alibaba.nacos.client.naming: warn
# ===============================
# = Spring Config
# ===============================
spring:
  redis:
    url: redis://127.0.0.1:6379
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  cloud:
    nacos:
      discovery:
        ip: ${server.address}
    bus:
      id: ${spring.application.name}:${server.address}:${server.port}:v${info.version}:${spring.profiles.active}
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: 127.0.0.1:9092
          # 0代表：不进行消息接收是否成功的确认(默认值)；
          # 1代表：当Leader副本接收成功后，返回接收成功确认信息；
          # -1代表：当Leader和Follower副本都接收成功后，返回接收成功确认信息；
          required-acks: -1
  # ===============================
  # = JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  # ===============================
  # = DATA SOURCE
  # ===============================
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/acp-admin?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC&useSSL=false
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
# ===============================
# = Security Config
# ===============================
security:
  oauth2:
    client:
      client-id: 8a80cb816d2eb97f016d2eba04710000
      client-secret: 2523342F2BD345EA9658452A289364AA
acp:
  swagger:
    enabled: true