server:
  port: ${acp_server_port:0}
# ===============================
# = Log To File Config
# ===============================
logging:
  file:
    path: ${acp_log_path:logs/${spring.application.name}}
    name: ${logging.file.path}/${spring.application.name}.log
# ===============================
# = Spring Config
# ===============================
spring:
  # ===============================
  # = DATA SOURCE
  # ===============================
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/acp-admin?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC&useSSL=false
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
acp:
  schedule:
    cron:
      LogFileBackUpTask: 0 0/1 * * * ?
      LogDailyHistory: 0 0/1 * * * ?