debug: false
server:
  address: 127.0.0.1
  port: 8780
# ===============================
# = Log To File Config
# ===============================
logging:
  path: logs/log-server
  pattern:
    file: '[%date{yyyy-MM-dd HH:mm:ss.SSS}] [ %-5level] [%thread] %logger{96} [%X{lineno}] - %msg%n'
  file:
    max-size: 5MB
    max-history: 30
# ===============================
# = Eureka Config
# ===============================
eureka:
  instance:
    ip-address: ${server.address}
    instance-id: ${spring.application.name}(${server.address}:${server.port}):v${info.version}:${spring.profiles.active}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
# ===============================
# = Spring Config
# ===============================
spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: 127.0.0.1:9092
      bindings:
        log_output:
          binder: kafka
          consumer:
            headerMode: raw
          producer:
            headerMode: raw
          # topic
          destination: app-log
          group: app-log-group
          content-type: application/json
        # 与@StreamListener注解中的value一致，是绑定的渠道名
        log_input:
          binder: kafka
          consumer:
            headerMode: raw
          producer:
            headerMode: raw
          # topic
          destination: app-log
          group: app-log-group
          content-type: application/json
# ===============================
# = Security Config
# ===============================
security:
  oauth2:
    client:
      client-id: client
      client-secret: client
acp:
  schedule:
    crons:
      LogFileBackUpTask: 0 5 0 * * ?