server:
  address: 127.0.0.1
  port: 8771
management:
  server:
    port: 8770
# ===============================
# = Log To File Config
# ===============================
logging:
  file:
    path: logs/gateway-server
    name: ${logging.file.path}/${spring.application.name}.log
# ===============================
# = Spring Config
# ===============================
spring:
  cloud:
    nacos:
      discovery:
        ip: ${server.address}