server:
  port: 8771
# ===============================
# = Log To File Config
# ===============================
logging:
  file:
    path: logs/gateway-server
    name: ${logging.file.path}/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
  level:
    com.alibaba.nacos.client: warn
    org.springframework.cloud.function: warn