server:
  address: 127.0.0.1
  port: 8771
management:
  server:
    port: 8770
# ===============================
# = Log To File Config
# ===============================
logging:
  path: logs/gateway-server
  pattern:
    file: '[%date{yyyy-MM-dd HH:mm:ss.SSS}] [ %-5level] [%thread] %logger{96} [%X{lineno}] - %msg%n'
  file: ${logging.path}/${spring.application.name}.log
logging.file.max-size: 5MB
logging.file.max-history: 30
logging.level.com.alibaba.nacos.client.naming: warn
# ===============================
# = Spring Config
# ===============================
spring:
  redis:
    url: redis://127.0.0.1:6379
  kafka:
    bootstrap-servers: ${spring.cloud.stream.kafka.binder.brokers}
  cloud:
    nacos:
      discovery:
        ip: ${server.address}
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: 127.0.0.1:9092
          # 0代表：不进行消息接收是否成功的确认(默认值)；
          # 1代表：当Leader副本接收成功后，返回接收成功确认信息；
          # -1代表：当Leader和Follower副本都接收成功后，返回接收成功确认信息；
          required-acks: -1